name: Track push
on:
  push:
    branches: [main, accept]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Google Chat Notification
      env:
        sender: ${{ github.event.sender.login }}
        sender: ${{ github.event.head_commit.timestamp }}
        sender: ${{ github.event.head_commit.message }}
        sender: ${{ github.event.head_commit.url }}
      run: |
          curl --location --request POST 'https://chat.googleapis.com/v1/spaces/AAAAZAydlOI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=XN80owiMh-zLLM1AyxRCs_6hnhukpKBgIeCbHaxy1G4%3D' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "text": "'${{ github.event.sender.login }}' pushed a commit to accept on '${{ github.event.head_commit.timestamp }}' with message '${{ github.event.head_commit.message }}' and url '${{ github.event.head_commit.url }}'"
          }'